# Generated by Django 4.2.7 on 2024-11-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('mobileno', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
