# Generated by Django 4.2.7 on 2024-11-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0003_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
